#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the server hostname

sudo apt-get update -y
sudo apt-get install -y nginx

# Add the custom header to the Nginx config
sudo sed -i "/server_name _;/a \\	add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
