#!/usr/bin/env bash
# Configure nginx with custom header

apt-get update -y
apt-get install -y nginx

echo "Holberton School" >/var/www/html/index.nginx-debian.html

# Add the header
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
