#!/usr/bin/env bash
# Installs and configures HAproxy on a new Ubuntu machine
# to load balance traffic to web-01 and web-02 using roundrobin.

apt-get update
apt-get install -y haproxy

# Enable HAproxy to be managed via init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Append load balancer config to existing haproxy.cfg
cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server ${HOSTNAME}-web-01 ${HOSTNAME}-web-01:80 check
    server ${HOSTNAME}-web-02 ${HOSTNAME}-web-02:80 check
EOF

service haproxy restart

